In [10]:
# car(자동차) 테이블생성
import MySQLdb
import csv

# MySQL 연결 정보
host = 'localhost'
user = 'root'
password = '12345'
database = 'carini'
port = 3306

try:
    # 데이터베이스에 연결
    conn = MySQLdb.connect(host=host, user=user, password=password, database=database, port=port)

    # 커서 생성
    cursor = conn.cursor()
    sql =''' 
        create table car(
             CAR_ID              int AUTO_INCREMENT PRIMARY KEY
           , CAR_NAME            varchar(255)
           , CAR_MIN_PRICE       int
           , CAR_MAX_PRICE       int
           , CAR_SIZE            varchar(255)
           , CAR_FUEL            varchar(255)
           , CAR_EFF             varchar(255)
           , CAR_IMG             varchar(255)
           , CAR_SC_PER          double
           , CAR_SC_PRICE        double
           , CAR_SC_GEOJU        double
           , CAR_SC_QUALITY      double
           , CAR_SC_DESIGN       double
           , CAR_SC_EFF          double
           , CAR_SC_AVG          double
        );'''
    cursor.execute(sql)

    # 변경사항 커밋
    conn.commit()

except Exception as e:
    # 예외 발생 시 롤백
    conn.rollback()
    # 예외 내용 출력
    print("Error:", e)

finally:
    # 연결 종료
    conn.close()

In [12]:
# car_data_onlynum.csv 파일의 데이터를 DB에 넣는 코드
import MySQLdb
import csv

# MySQL 연결 정보
host = 'localhost'
user = 'root'
password = '12345'
database = 'carini'
port = 3306

try:
    # 데이터베이스에 연결
    conn = MySQLdb.connect(host=host, user=user, password=password, database=database, port=port)

    # 커서 생성
    cursor = conn.cursor()

    # csv 파일의 경로
    csv_file_path = "./data/car_data_onlynum.csv"

    # csv 데이터 넣기
    with open(csv_file_path, 'r', encoding='cp949') as file:
        csv_data = csv.reader(file)
        next(csv_data)  # 헤더 스킵
        for row in csv_data:
            query = """
                INSERT INTO car (CAR_NAME, CAR_MIN_PRICE, CAR_MAX_PRICE, CAR_SIZE, CAR_FUEL, CAR_EFF , CAR_IMG,
                CAR_SC_PER, CAR_SC_PRICE, CAR_SC_GEOJU, CAR_SC_QUALITY, CAR_SC_DESIGN, CAR_SC_EFF, CAR_SC_AVG)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                """
            values = (row[0], row[1], row[2], row[3], row[4], row[5], row[6], row[7], row[8], row[9], row[10], row[11], row[12], row[13])
            cursor.execute(query, values)

    # 변경사항 커밋
    conn.commit()

except Exception as e:
    # 예외 발생 시 롤백
    conn.rollback()
    # 예외 내용 출력
    print("Error:", e)

finally:
    # 연결 종료
    conn.close()

In [13]:
# member(회원정보) 테이블생성
import MySQLdb
import csv

# MySQL 연결 정보
host = 'localhost'
user = 'root'
password = '12345'
database = 'carini'
port = 3306

try:
    # 데이터베이스에 연결
    conn = MySQLdb.connect(host=host, user=user, password=password, database=database, port=port)

    # 커서 생성
    cursor = conn.cursor()
    sql =''' 
        create table member(
             MEMBER_NUM           int AUTO_INCREMENT PRIMARY KEY
           , MEMBER_ID            varchar(255)
           , MEMBER_PW            varchar(255)
           , MEMBER_NAME          varchar(255)
           , MEMBER_NICNAME       varchar(255)
           , MEMBER_EMAIL         varchar(255)
           , MEMBER_PHONENUM      varchar(255)
           , MEMBER_JOIN_DATE     date
           , MEMBER_SOCIAL        varchar(255)
           , MEMBER_ROLE          varchar(255)
        );'''
    cursor.execute(sql)

    # 변경사항 커밋
    conn.commit()

except Exception as e:
    # 예외 발생 시 롤백
    conn.rollback()
    # 예외 내용 출력
    print("Error:", e)

finally:
    # 연결 종료
    conn.close()

In [14]:
# board(게시판) 테이블생성
import MySQLdb
import csv

# MySQL 연결 정보
host = 'localhost'
user = 'root'
password = '12345'
database = 'carini'
port = 3306

try:
    # 데이터베이스에 연결
    conn = MySQLdb.connect(host=host, user=user, password=password, database=database, port=port)

    # 커서 생성
    cursor = conn.cursor()
    sql =''' 
        create table board(
             BOARD_ID           int AUTO_INCREMENT PRIMARY KEY
           , BOARD_WRITER       varchar(255)
           , BOARD_TITLE        varchar(255)
           , BOARD_CONTENT      varchar(255)
           , BOARD_FILE         varchar(255)
           , BOARD_DATE         date
        );'''
    cursor.execute(sql)

    # 변경사항 커밋
    conn.commit()

except Exception as e:
    # 예외 발생 시 롤백
    conn.rollback()
    # 예외 내용 출력
    print("Error:", e)

finally:
    # 연결 종료
    conn.close()

In [15]:
# bookmark(즐겨찾기) 테이블생성
import MySQLdb
import csv

# MySQL 연결 정보
host = 'localhost'
user = 'root'
password = '12345'
database = 'carini'
port = 3306

try:
    # 데이터베이스에 연결
    conn = MySQLdb.connect(host=host, user=user, password=password, database=database, port=port)

    # 커서 생성
    cursor = conn.cursor()
    sql =''' 
                create table bookmark(
                     MEMBER_NUM          int
                   , BOOKMARK_CAR_ID     int
    );'''
    cursor.execute(sql)

    # 변경사항 커밋
    conn.commit()

except Exception as e:
    # 예외 발생 시 롤백
    conn.rollback()
    # 예외 내용 출력
    print("Error:", e)

finally:
    # 연결 종료
    conn.close()

In [16]:
# notice(공지사항) 테이블생성
import MySQLdb
import csv

# MySQL 연결 정보
host = 'localhost'
user = 'root'
password = '12345'
database = 'carini'
port = 3306

try:
    # 데이터베이스에 연결
    conn = MySQLdb.connect(host=host, user=user, password=password, database=database, port=port)

    # 커서 생성
    cursor = conn.cursor()
    sql =''' 
                create table notice(
                     NOTICE_ID          int AUTO_INCREMENT PRIMARY KEY
                   , NOTICE_WRITER     varchar(255)
                   , NOTICE_TITLE      varchar(255)
                   , NOTICE_CONTENT    varchar(255)
                   , NOTICE_FILE       varchar(255)
                   , NOTICE_DATE       date
        );'''
    cursor.execute(sql)

    # 변경사항 커밋
    conn.commit()

except Exception as e:
    # 예외 발생 시 롤백
    conn.rollback()
    # 예외 내용 출력
    print("Error:", e)

finally:
    # 연결 종료
    conn.close()

In [18]:
# inquiry(문의) 테이블생성
import MySQLdb
import csv

# MySQL 연결 정보
host = 'localhost'
user = 'root'
password = '12345'
database = 'carini'
port = 3306

try:
    # 데이터베이스에 연결
    conn = MySQLdb.connect(host=host, user=user, password=password, database=database, port=port)

    # 커서 생성
    cursor = conn.cursor()

    sql =''' 
        create table inquiry(
               MEMBER_NUM      int
             , RE_ID           int AUTO_INCREMENT PRIMARY KEY
             , RE_DATE         date
             , RE_CONTENT      varchar(255)
             , RE_HERO         varchar(255)
             , RE_DATE_RQ      date
             , RE_CONTENT_RQ   varchar(255)
             , RE_CHECK_RQ     varchar(255)
             );'''
    cursor.execute(sql)

    # 변경사항 커밋
    conn.commit()

except Exception as e:
    # 예외 발생 시 롤백
    conn.rollback()
    # 예외 내용 출력
    print("Error:", e)

finally:
    # 연결 종료
    conn.close()

In [19]:
# agency(대리점) 테이블생성
import MySQLdb
import csv

# MySQL 연결 정보
host = 'localhost'
user = 'root'
password = '12345'
database = 'carini'
port = 3306

try:
    # 데이터베이스에 연결
    conn = MySQLdb.connect(host=host, user=user, password=password, database=database, port=port)

    # 커서 생성
    cursor = conn.cursor()

    sql =''' 
        create table agency(
               CAR_BRAND       varchar(255)
             , AGENCY_NAME     varchar(255)
             , AGENCY_ADDRESS  varchar(255)
             , AGENCY_LAT      varchar(255)
             , AGENCY_LON      varchar(255)
             , AGENCY_TEL      varchar(255)
             );'''
    cursor.execute(sql)

    # 변경사항 커밋
    conn.commit()

except Exception as e:
    # 예외 발생 시 롤백
    conn.rollback()
    # 예외 내용 출력
    print("Error:", e)

finally:
    # 연결 종료
    conn.close()

In [20]:
# agency.csv 파일의 데이터를 DB에 넣는 코드
import MySQLdb
import csv

# MySQL 연결 정보
host = 'localhost'
user = 'root'
password = '12345'
database = 'carini'
port = 3306

try:
    # 데이터베이스에 연결
    conn = MySQLdb.connect(host=host, user=user, password=password, database=database, port=port)

    # 커서 생성
    cursor = conn.cursor()

    # csv 파일의 경로
    csv_file_path = "./data/agency.csv"

    # csv 데이터 넣기
    with open(csv_file_path, 'r', encoding='utf-8') as file:
        csv_data = csv.reader(file)
        next(csv_data)  # 헤더 스킵
        for row in csv_data:
            query = """
                INSERT INTO agency (CAR_BRAND, AGENCY_NAME, AGENCY_ADDRESS, AGENCY_LAT, AGENCY_LON, AGENCY_TEL)
                VALUES (%s, %s, %s, %s, %s, %s)
                """
            values = (row[0], row[1], row[2], row[3], row[4], row[5])
            cursor.execute(query, values)

    # 변경사항 커밋
    conn.commit()

except Exception as e:
    # 예외 발생 시 롤백
    conn.rollback()
    # 예외 내용 출력
    print("Error:", e)

finally:
    # 연결 종료
    conn.close()